max-raycast-length=10.0
segment-depth=0.03
smooth-iterations=2

pencil.default-radius=0.05
pencil.min-radius=0.01
pencil.max-radius=0.1
pencil.radius-step=0.01

eraser.default-radius=0.5
eraser.min-radius=0.125
eraser.max-radius=4.0
eraser.radius-step=0.125
