name: AirBrush
version: '${version}'

main: br.com.vrosa.airbrush.paper.AirBrush
bootstrapper: br.com.vrosa.airbrush.paper.AirBrushBootstrap
loader: br.com.vrosa.airbrush.paper.AirBrushLoader
api-version: '26.1.2'
load: POSTWORLD

authors: [ ShiftSad ]
